// @ts-check
// Flat ESLint config generated by the @nuxt/eslint module (.nuxt/eslint.config.mjs).
import withNuxt from './.nuxt/eslint.config.mjs'

export default withNuxt({
  rules: {
    // Single-word page/layout names are idiomatic in Nuxt.
    'vue/multi-word-component-names': 'off',
  },
})
